// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/edu_organization_service.go
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	domain "bum-service/internal/domain"
	director "bum-service/internal/service/director"
	eduorganization "bum-service/internal/service/edu-organization"
	grades "bum-service/internal/service/grade-standard"
	headmaster "bum-service/internal/service/headmaster"
	school "bum-service/internal/service/school"
	student "bum-service/internal/service/student"
	subject "bum-service/internal/service/subject"
	teacher "bum-service/internal/service/teacher"
	user "bum-service/internal/service/user"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockISystemService is a mock of ISystemService interface.
type MockISystemService struct {
	ctrl     *gomock.Controller
	recorder *MockISystemServiceMockRecorder
}

// MockISystemServiceMockRecorder is the mock recorder for MockISystemService.
type MockISystemServiceMockRecorder struct {
	mock *MockISystemService
}

// NewMockISystemService creates a new mock instance.
func NewMockISystemService(ctrl *gomock.Controller) *MockISystemService {
	mock := &MockISystemService{ctrl: ctrl}
	mock.recorder = &MockISystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISystemService) EXPECT() *MockISystemServiceMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockISystemService) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockISystemServiceMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockISystemService)(nil).HealthCheck), ctx)
}

// MockIEduOrganizationService is a mock of IEduOrganizationService interface.
type MockIEduOrganizationService struct {
	ctrl     *gomock.Controller
	recorder *MockIEduOrganizationServiceMockRecorder
}

// MockIEduOrganizationServiceMockRecorder is the mock recorder for MockIEduOrganizationService.
type MockIEduOrganizationServiceMockRecorder struct {
	mock *MockIEduOrganizationService
}

// NewMockIEduOrganizationService creates a new mock instance.
func NewMockIEduOrganizationService(ctrl *gomock.Controller) *MockIEduOrganizationService {
	mock := &MockIEduOrganizationService{ctrl: ctrl}
	mock.recorder = &MockIEduOrganizationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEduOrganizationService) EXPECT() *MockIEduOrganizationServiceMockRecorder {
	return m.recorder
}

// CreateEduOrganization mocks base method.
func (m *MockIEduOrganizationService) CreateEduOrganization(ctx context.Context, args eduorganization.CreateEduOrganizationArgs) (domain.EduOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEduOrganization", ctx, args)
	ret0, _ := ret[0].(domain.EduOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEduOrganization indicates an expected call of CreateEduOrganization.
func (mr *MockIEduOrganizationServiceMockRecorder) CreateEduOrganization(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEduOrganization", reflect.TypeOf((*MockIEduOrganizationService)(nil).CreateEduOrganization), ctx, args)
}

// EduOrganizationByID mocks base method.
func (m *MockIEduOrganizationService) EduOrganizationByID(ctx context.Context, id uuid.UUID) (domain.EduOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EduOrganizationByID", ctx, id)
	ret0, _ := ret[0].(domain.EduOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EduOrganizationByID indicates an expected call of EduOrganizationByID.
func (mr *MockIEduOrganizationServiceMockRecorder) EduOrganizationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EduOrganizationByID", reflect.TypeOf((*MockIEduOrganizationService)(nil).EduOrganizationByID), ctx, id)
}

// EduOrganizationList mocks base method.
func (m *MockIEduOrganizationService) EduOrganizationList(ctx context.Context, filters domain.EduOrganizationFilters) (domain.EduOrganizations, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EduOrganizationList", ctx, filters)
	ret0, _ := ret[0].(domain.EduOrganizations)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EduOrganizationList indicates an expected call of EduOrganizationList.
func (mr *MockIEduOrganizationServiceMockRecorder) EduOrganizationList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EduOrganizationList", reflect.TypeOf((*MockIEduOrganizationService)(nil).EduOrganizationList), ctx, filters)
}

// UpdateEduOrganizationByID mocks base method.
func (m *MockIEduOrganizationService) UpdateEduOrganizationByID(ctx context.Context, args eduorganization.UpdateEduOrganizationArgs) (domain.EduOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEduOrganizationByID", ctx, args)
	ret0, _ := ret[0].(domain.EduOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEduOrganizationByID indicates an expected call of UpdateEduOrganizationByID.
func (mr *MockIEduOrganizationServiceMockRecorder) UpdateEduOrganizationByID(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEduOrganizationByID", reflect.TypeOf((*MockIEduOrganizationService)(nil).UpdateEduOrganizationByID), ctx, args)
}

// MockISchoolService is a mock of ISchoolService interface.
type MockISchoolService struct {
	ctrl     *gomock.Controller
	recorder *MockISchoolServiceMockRecorder
}

// MockISchoolServiceMockRecorder is the mock recorder for MockISchoolService.
type MockISchoolServiceMockRecorder struct {
	mock *MockISchoolService
}

// NewMockISchoolService creates a new mock instance.
func NewMockISchoolService(ctrl *gomock.Controller) *MockISchoolService {
	mock := &MockISchoolService{ctrl: ctrl}
	mock.recorder = &MockISchoolServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISchoolService) EXPECT() *MockISchoolServiceMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockISchoolService) CreateGroup(ctx context.Context, arg school.CreateGroupArgs) (domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, arg)
	ret0, _ := ret[0].(domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockISchoolServiceMockRecorder) CreateGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockISchoolService)(nil).CreateGroup), ctx, arg)
}

// CreateSchool mocks base method.
func (m *MockISchoolService) CreateSchool(ctx context.Context, args school.CreateSchoolArgs) (domain.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchool", ctx, args)
	ret0, _ := ret[0].(domain.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchool indicates an expected call of CreateSchool.
func (mr *MockISchoolServiceMockRecorder) CreateSchool(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchool", reflect.TypeOf((*MockISchoolService)(nil).CreateSchool), ctx, args)
}

// CreateSchoolSubject mocks base method.
func (m *MockISchoolService) CreateSchoolSubject(ctx context.Context, args school.CreateSchoolSubjectArgs) (domain.SchoolSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchoolSubject", ctx, args)
	ret0, _ := ret[0].(domain.SchoolSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchoolSubject indicates an expected call of CreateSchoolSubject.
func (mr *MockISchoolServiceMockRecorder) CreateSchoolSubject(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchoolSubject", reflect.TypeOf((*MockISchoolService)(nil).CreateSchoolSubject), ctx, args)
}

// GroupByID mocks base method.
func (m *MockISchoolService) GroupByID(ctx context.Context, schoolID, groupID uuid.UUID) (domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupByID", ctx, schoolID, groupID)
	ret0, _ := ret[0].(domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupByID indicates an expected call of GroupByID.
func (mr *MockISchoolServiceMockRecorder) GroupByID(ctx, schoolID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupByID", reflect.TypeOf((*MockISchoolService)(nil).GroupByID), ctx, schoolID, groupID)
}

// GroupList mocks base method.
func (m *MockISchoolService) GroupList(ctx context.Context, schoolID uuid.UUID, filters domain.GroupFilters) (domain.Grades, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupList", ctx, schoolID, filters)
	ret0, _ := ret[0].(domain.Grades)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GroupList indicates an expected call of GroupList.
func (mr *MockISchoolServiceMockRecorder) GroupList(ctx, schoolID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupList", reflect.TypeOf((*MockISchoolService)(nil).GroupList), ctx, schoolID, filters)
}

// SchoolByID mocks base method.
func (m *MockISchoolService) SchoolByID(ctx context.Context, schoolID uuid.UUID) (domain.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchoolByID", ctx, schoolID)
	ret0, _ := ret[0].(domain.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SchoolByID indicates an expected call of SchoolByID.
func (mr *MockISchoolServiceMockRecorder) SchoolByID(ctx, schoolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchoolByID", reflect.TypeOf((*MockISchoolService)(nil).SchoolByID), ctx, schoolID)
}

// SchoolList mocks base method.
func (m *MockISchoolService) SchoolList(ctx context.Context, filters domain.SchoolFilters) (domain.Schools, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchoolList", ctx, filters)
	ret0, _ := ret[0].(domain.Schools)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SchoolList indicates an expected call of SchoolList.
func (mr *MockISchoolServiceMockRecorder) SchoolList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchoolList", reflect.TypeOf((*MockISchoolService)(nil).SchoolList), ctx, filters)
}

// SchoolSubjectByIDAndSchoolID mocks base method.
func (m *MockISchoolService) SchoolSubjectByIDAndSchoolID(ctx context.Context, id, schoolID uuid.UUID) (domain.SchoolSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchoolSubjectByIDAndSchoolID", ctx, id, schoolID)
	ret0, _ := ret[0].(domain.SchoolSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SchoolSubjectByIDAndSchoolID indicates an expected call of SchoolSubjectByIDAndSchoolID.
func (mr *MockISchoolServiceMockRecorder) SchoolSubjectByIDAndSchoolID(ctx, id, schoolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchoolSubjectByIDAndSchoolID", reflect.TypeOf((*MockISchoolService)(nil).SchoolSubjectByIDAndSchoolID), ctx, id, schoolID)
}

// SchoolSubjectList mocks base method.
func (m *MockISchoolService) SchoolSubjectList(ctx context.Context, filters domain.SchoolSubjectFilters) (domain.SchoolSubjects, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchoolSubjectList", ctx, filters)
	ret0, _ := ret[0].(domain.SchoolSubjects)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SchoolSubjectList indicates an expected call of SchoolSubjectList.
func (mr *MockISchoolServiceMockRecorder) SchoolSubjectList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchoolSubjectList", reflect.TypeOf((*MockISchoolService)(nil).SchoolSubjectList), ctx, filters)
}

// MockIDirectorService is a mock of IDirectorService interface.
type MockIDirectorService struct {
	ctrl     *gomock.Controller
	recorder *MockIDirectorServiceMockRecorder
}

// MockIDirectorServiceMockRecorder is the mock recorder for MockIDirectorService.
type MockIDirectorServiceMockRecorder struct {
	mock *MockIDirectorService
}

// NewMockIDirectorService creates a new mock instance.
func NewMockIDirectorService(ctrl *gomock.Controller) *MockIDirectorService {
	mock := &MockIDirectorService{ctrl: ctrl}
	mock.recorder = &MockIDirectorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDirectorService) EXPECT() *MockIDirectorServiceMockRecorder {
	return m.recorder
}

// AddDirector mocks base method.
func (m *MockIDirectorService) AddDirector(ctx context.Context, args director.AddDirectorArgs) (domain.Director, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDirector", ctx, args)
	ret0, _ := ret[0].(domain.Director)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDirector indicates an expected call of AddDirector.
func (mr *MockIDirectorServiceMockRecorder) AddDirector(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDirector", reflect.TypeOf((*MockIDirectorService)(nil).AddDirector), ctx, args)
}

// DirectorByID mocks base method.
func (m *MockIDirectorService) DirectorByID(ctx context.Context, id uuid.UUID) (domain.Director, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectorByID", ctx, id)
	ret0, _ := ret[0].(domain.Director)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectorByID indicates an expected call of DirectorByID.
func (mr *MockIDirectorServiceMockRecorder) DirectorByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectorByID", reflect.TypeOf((*MockIDirectorService)(nil).DirectorByID), ctx, id)
}

// DirectorList mocks base method.
func (m *MockIDirectorService) DirectorList(ctx context.Context, filters domain.DirectorListFilter) ([]domain.Director, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectorList", ctx, filters)
	ret0, _ := ret[0].([]domain.Director)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DirectorList indicates an expected call of DirectorList.
func (mr *MockIDirectorServiceMockRecorder) DirectorList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectorList", reflect.TypeOf((*MockIDirectorService)(nil).DirectorList), ctx, filters)
}

// MockIHeadmasterService is a mock of IHeadmasterService interface.
type MockIHeadmasterService struct {
	ctrl     *gomock.Controller
	recorder *MockIHeadmasterServiceMockRecorder
}

// MockIHeadmasterServiceMockRecorder is the mock recorder for MockIHeadmasterService.
type MockIHeadmasterServiceMockRecorder struct {
	mock *MockIHeadmasterService
}

// NewMockIHeadmasterService creates a new mock instance.
func NewMockIHeadmasterService(ctrl *gomock.Controller) *MockIHeadmasterService {
	mock := &MockIHeadmasterService{ctrl: ctrl}
	mock.recorder = &MockIHeadmasterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHeadmasterService) EXPECT() *MockIHeadmasterServiceMockRecorder {
	return m.recorder
}

// AddHeadmaster mocks base method.
func (m *MockIHeadmasterService) AddHeadmaster(ctx context.Context, args headmaster.AddHeadmasterArgs) (domain.Headmaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHeadmaster", ctx, args)
	ret0, _ := ret[0].(domain.Headmaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddHeadmaster indicates an expected call of AddHeadmaster.
func (mr *MockIHeadmasterServiceMockRecorder) AddHeadmaster(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeadmaster", reflect.TypeOf((*MockIHeadmasterService)(nil).AddHeadmaster), ctx, args)
}

// HeadmasterByID mocks base method.
func (m *MockIHeadmasterService) HeadmasterByID(ctx context.Context, id uuid.UUID) (domain.Headmaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadmasterByID", ctx, id)
	ret0, _ := ret[0].(domain.Headmaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadmasterByID indicates an expected call of HeadmasterByID.
func (mr *MockIHeadmasterServiceMockRecorder) HeadmasterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadmasterByID", reflect.TypeOf((*MockIHeadmasterService)(nil).HeadmasterByID), ctx, id)
}

// HeadmasterList mocks base method.
func (m *MockIHeadmasterService) HeadmasterList(ctx context.Context, filters domain.HeadmasterListFilter) ([]domain.Headmaster, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadmasterList", ctx, filters)
	ret0, _ := ret[0].([]domain.Headmaster)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HeadmasterList indicates an expected call of HeadmasterList.
func (mr *MockIHeadmasterServiceMockRecorder) HeadmasterList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadmasterList", reflect.TypeOf((*MockIHeadmasterService)(nil).HeadmasterList), ctx, filters)
}

// MockISubjectService is a mock of ISubjectService interface.
type MockISubjectService struct {
	ctrl     *gomock.Controller
	recorder *MockISubjectServiceMockRecorder
}

// MockISubjectServiceMockRecorder is the mock recorder for MockISubjectService.
type MockISubjectServiceMockRecorder struct {
	mock *MockISubjectService
}

// NewMockISubjectService creates a new mock instance.
func NewMockISubjectService(ctrl *gomock.Controller) *MockISubjectService {
	mock := &MockISubjectService{ctrl: ctrl}
	mock.recorder = &MockISubjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISubjectService) EXPECT() *MockISubjectServiceMockRecorder {
	return m.recorder
}

// CreateSubject mocks base method.
func (m *MockISubjectService) CreateSubject(ctx context.Context, args subject.CreateSubjectArgs) (domain.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubject", ctx, args)
	ret0, _ := ret[0].(domain.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubject indicates an expected call of CreateSubject.
func (mr *MockISubjectServiceMockRecorder) CreateSubject(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubject", reflect.TypeOf((*MockISubjectService)(nil).CreateSubject), ctx, args)
}

// SubjectByID mocks base method.
func (m *MockISubjectService) SubjectByID(ctx context.Context, id uuid.UUID) (domain.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectByID", ctx, id)
	ret0, _ := ret[0].(domain.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubjectByID indicates an expected call of SubjectByID.
func (mr *MockISubjectServiceMockRecorder) SubjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectByID", reflect.TypeOf((*MockISubjectService)(nil).SubjectByID), ctx, id)
}

// SubjectList mocks base method.
func (m *MockISubjectService) SubjectList(ctx context.Context, filters domain.SubjectListFilter) ([]domain.Subject, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectList", ctx, filters)
	ret0, _ := ret[0].([]domain.Subject)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubjectList indicates an expected call of SubjectList.
func (mr *MockISubjectServiceMockRecorder) SubjectList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectList", reflect.TypeOf((*MockISubjectService)(nil).SubjectList), ctx, filters)
}

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockIUserService) AddUser(ctx context.Context, args user.AddUserArgs) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, args)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser.
func (mr *MockIUserServiceMockRecorder) AddUser(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockIUserService)(nil).AddUser), ctx, args)
}

// UserByID mocks base method.
func (m *MockIUserService) UserByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockIUserServiceMockRecorder) UserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockIUserService)(nil).UserByID), ctx, id)
}

// UserList mocks base method.
func (m *MockIUserService) UserList(ctx context.Context, filters domain.UserListFilter) (domain.Users, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserList", ctx, filters)
	ret0, _ := ret[0].(domain.Users)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserList indicates an expected call of UserList.
func (mr *MockIUserServiceMockRecorder) UserList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserList", reflect.TypeOf((*MockIUserService)(nil).UserList), ctx, filters)
}

// UserRoles mocks base method.
func (m *MockIUserService) UserRoles(ctx context.Context, id uuid.UUID) (domain.UserRoles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRoles", ctx, id)
	ret0, _ := ret[0].(domain.UserRoles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserRoles indicates an expected call of UserRoles.
func (mr *MockIUserServiceMockRecorder) UserRoles(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRoles", reflect.TypeOf((*MockIUserService)(nil).UserRoles), ctx, id)
}

// MockITeacherService is a mock of ITeacherService interface.
type MockITeacherService struct {
	ctrl     *gomock.Controller
	recorder *MockITeacherServiceMockRecorder
}

// MockITeacherServiceMockRecorder is the mock recorder for MockITeacherService.
type MockITeacherServiceMockRecorder struct {
	mock *MockITeacherService
}

// NewMockITeacherService creates a new mock instance.
func NewMockITeacherService(ctrl *gomock.Controller) *MockITeacherService {
	mock := &MockITeacherService{ctrl: ctrl}
	mock.recorder = &MockITeacherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITeacherService) EXPECT() *MockITeacherServiceMockRecorder {
	return m.recorder
}

// AddTeacher mocks base method.
func (m *MockITeacherService) AddTeacher(ctx context.Context, args teacher.AddTeacherArgs) (domain.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeacher", ctx, args)
	ret0, _ := ret[0].(domain.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTeacher indicates an expected call of AddTeacher.
func (mr *MockITeacherServiceMockRecorder) AddTeacher(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeacher", reflect.TypeOf((*MockITeacherService)(nil).AddTeacher), ctx, args)
}

// TeacherByID mocks base method.
func (m *MockITeacherService) TeacherByID(ctx context.Context, id uuid.UUID) (domain.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeacherByID", ctx, id)
	ret0, _ := ret[0].(domain.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TeacherByID indicates an expected call of TeacherByID.
func (mr *MockITeacherServiceMockRecorder) TeacherByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeacherByID", reflect.TypeOf((*MockITeacherService)(nil).TeacherByID), ctx, id)
}

// TeacherList mocks base method.
func (m *MockITeacherService) TeacherList(ctx context.Context, filters domain.TeacherListFilter) (domain.Teachers, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeacherList", ctx, filters)
	ret0, _ := ret[0].(domain.Teachers)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TeacherList indicates an expected call of TeacherList.
func (mr *MockITeacherServiceMockRecorder) TeacherList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeacherList", reflect.TypeOf((*MockITeacherService)(nil).TeacherList), ctx, filters)
}

// MockIGradesService is a mock of IGradesService interface.
type MockIGradesService struct {
	ctrl     *gomock.Controller
	recorder *MockIGradesServiceMockRecorder
}

// MockIGradesServiceMockRecorder is the mock recorder for MockIGradesService.
type MockIGradesServiceMockRecorder struct {
	mock *MockIGradesService
}

// NewMockIGradesService creates a new mock instance.
func NewMockIGradesService(ctrl *gomock.Controller) *MockIGradesService {
	mock := &MockIGradesService{ctrl: ctrl}
	mock.recorder = &MockIGradesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGradesService) EXPECT() *MockIGradesServiceMockRecorder {
	return m.recorder
}

// CreateGradeStandard mocks base method.
func (m *MockIGradesService) CreateGradeStandard(ctx context.Context, arg grades.CreateGradeStandardArgs) (domain.GradeStandard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGradeStandard", ctx, arg)
	ret0, _ := ret[0].(domain.GradeStandard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGradeStandard indicates an expected call of CreateGradeStandard.
func (mr *MockIGradesServiceMockRecorder) CreateGradeStandard(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGradeStandard", reflect.TypeOf((*MockIGradesService)(nil).CreateGradeStandard), ctx, arg)
}

// GradeStandardByID mocks base method.
func (m *MockIGradesService) GradeStandardByID(ctx context.Context, id uuid.UUID) (domain.GradeStandard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GradeStandardByID", ctx, id)
	ret0, _ := ret[0].(domain.GradeStandard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GradeStandardByID indicates an expected call of GradeStandardByID.
func (mr *MockIGradesServiceMockRecorder) GradeStandardByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GradeStandardByID", reflect.TypeOf((*MockIGradesService)(nil).GradeStandardByID), ctx, id)
}

// GradeStandardList mocks base method.
func (m *MockIGradesService) GradeStandardList(ctx context.Context, filter domain.GradeStandardListFilter) (domain.GradeStandards, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GradeStandardList", ctx, filter)
	ret0, _ := ret[0].(domain.GradeStandards)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GradeStandardList indicates an expected call of GradeStandardList.
func (mr *MockIGradesServiceMockRecorder) GradeStandardList(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GradeStandardList", reflect.TypeOf((*MockIGradesService)(nil).GradeStandardList), ctx, filter)
}

// MockIAuthService is a mock of IAuthService interface.
type MockIAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthServiceMockRecorder
}

// MockIAuthServiceMockRecorder is the mock recorder for MockIAuthService.
type MockIAuthServiceMockRecorder struct {
	mock *MockIAuthService
}

// NewMockIAuthService creates a new mock instance.
func NewMockIAuthService(ctrl *gomock.Controller) *MockIAuthService {
	mock := &MockIAuthService{ctrl: ctrl}
	mock.recorder = &MockIAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthService) EXPECT() *MockIAuthServiceMockRecorder {
	return m.recorder
}

// GetUserIDByEmailAndPassword mocks base method.
func (m *MockIAuthService) GetUserIDByEmailAndPassword(ctx context.Context, email, password string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByEmailAndPassword", ctx, email, password)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByEmailAndPassword indicates an expected call of GetUserIDByEmailAndPassword.
func (mr *MockIAuthServiceMockRecorder) GetUserIDByEmailAndPassword(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByEmailAndPassword", reflect.TypeOf((*MockIAuthService)(nil).GetUserIDByEmailAndPassword), ctx, email, password)
}

// MockIStudentService is a mock of IStudentService interface.
type MockIStudentService struct {
	ctrl     *gomock.Controller
	recorder *MockIStudentServiceMockRecorder
}

// MockIStudentServiceMockRecorder is the mock recorder for MockIStudentService.
type MockIStudentServiceMockRecorder struct {
	mock *MockIStudentService
}

// NewMockIStudentService creates a new mock instance.
func NewMockIStudentService(ctrl *gomock.Controller) *MockIStudentService {
	mock := &MockIStudentService{ctrl: ctrl}
	mock.recorder = &MockIStudentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStudentService) EXPECT() *MockIStudentServiceMockRecorder {
	return m.recorder
}

// AddStudent mocks base method.
func (m *MockIStudentService) AddStudent(ctx context.Context, args student.AddStudentArgs) (domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStudent", ctx, args)
	ret0, _ := ret[0].(domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStudent indicates an expected call of AddStudent.
func (mr *MockIStudentServiceMockRecorder) AddStudent(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStudent", reflect.TypeOf((*MockIStudentService)(nil).AddStudent), ctx, args)
}

// StudentByID mocks base method.
func (m *MockIStudentService) StudentByID(ctx context.Context, studentID uuid.UUID) (domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StudentByID", ctx, studentID)
	ret0, _ := ret[0].(domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StudentByID indicates an expected call of StudentByID.
func (mr *MockIStudentServiceMockRecorder) StudentByID(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StudentByID", reflect.TypeOf((*MockIStudentService)(nil).StudentByID), ctx, studentID)
}
