//nolint:nolintlint,errcheck,forcetypeassert,gocritic,ireturn,revive // this is mock that was generated
package liblog

import (
	"github.com/stretchr/testify/mock"
)

// MockLogger is an autogenerated mock type for the ILogger type.
type MockLogger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: args.
func (_m *MockLogger) Debug(args ...any) {
	var _ca []any
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Debugf provides a mock function with given fields: format, args.
func (_m *MockLogger) Debugf(format string, args ...any) {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: args.
func (_m *MockLogger) Error(args ...any) {
	var _ca []any
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Errorf provides a mock function with given fields: format, args.
func (_m *MockLogger) Errorf(format string, args ...any) {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Fatal provides a mock function with given fields: args.
func (_m *MockLogger) Fatal(args ...any) {
	var _ca []any
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Fatalf provides a mock function with given fields: format, args.
func (_m *MockLogger) Fatalf(format string, args ...any) {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: args.
func (_m *MockLogger) Info(args ...any) {
	var _ca []any
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Infof provides a mock function with given fields: format, args.
func (_m *MockLogger) Infof(format string, args ...any) {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Trace provides a mock function with given fields: args.
func (_m *MockLogger) Trace(args ...any) {
	var _ca []any
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Tracef provides a mock function with given fields: format, args.
func (_m *MockLogger) Tracef(format string, args ...any) {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warning provides a mock function with given fields: args.
func (_m *MockLogger) Warning(args ...any) {
	var _ca []any
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warningf provides a mock function with given fields: format, args.
func (_m *MockLogger) Warningf(format string, args ...any) {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WithLevel provides a mock function with given fields: level.
func (_m *MockLogger) WithLevel(level Level) LogFinalizer {
	ret := _m.Called(level)

	var r0 LogFinalizer
	if rf, ok := ret.Get(0).(func(Level) LogFinalizer); ok {
		r0 = rf(level)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(LogFinalizer)
		}
	}

	return r0
}

// WithFields provides a mock function with given fields: v.
func (_m *MockLogger) WithFields(v map[string]any) Logger {
	ret := _m.Called(v)

	var r0 Logger
	if rf, ok := ret.Get(0).(func(map[string]any) Logger); ok {
		r0 = rf(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Logger)
		}
	}

	return r0
}

// CallerWithSkipFrameCount provides a mock function with given fields: skipFrameCount.
func (_m *MockLogger) CallerWithSkipFrameCount(skipFrameCount int) Logger {
	ret := _m.Called(skipFrameCount)

	var r0 Logger
	if rf, ok := ret.Get(0).(func(int) Logger); ok {
		r0 = rf(skipFrameCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Logger)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup
// function to assert the mocks expectations.
func NewMockLogger(t mockConstructorTestingTNewMockLogger) *MockLogger {
	mockLog := &MockLogger{}
	mockLog.Mock.Test(t)

	t.Cleanup(func() { mockLog.AssertExpectations(t) })

	return mockLog
}
